version: "3.5"
services:
  pagina_inicial:
    image : httpd:2.4
    container_name: pagina_inicial
    volumes: 
      - ../:/usr/local/apache2/htdocs/
    stdin_open: true
    tty: true
    ports:
      - 1111:80
    healthcheck:
      test: curl --fail -s http://localhost:1111/ || exit 1
      interval: 30s
      timeout: 20s
      retries: 2
    restart: always